### PR TITLE
Fix message type link

### PR DESCRIPTION
**Pull request by Clayell**
The message type link in the docs doesn't exist, replaced it with a link that does.

**Terms**
- [x] I have read and understood this project's [Contributing Guidelines](CONTRIBUTING.md)

### CODE REVIEW

**Review by l-zeuch — APPROVED** [review]

**Comment by l-zeuch** [comment]
Nice catch, thanks!

**Comment by Clayell** [comment]
The Reaction Object at line 280 and 313 also need to be updated, but I'm not sure where those are.

**Comment by l-zeuch** [comment]
I'll try to find them tomorrow morning before I have to head to work 👍

**Comment by savage4618** [comment]
is this the one? 

https://discord.com/developers/docs/resources/message#reaction-object

**Pull request merged**
